# Site settings
title: Wu Yuan Gui's Blog
header-img: img/home-bg.jpg
email: wuyuangui@gmail.com
copyright_name: Wu Yuan Gui 
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/wuyuangui"
url: "http://yourdomain.com"
twitter_username: yuanguiwu 
github_username: lihuibng 
facebook_username: Wu Yuangui  
email_username:  wuyuangui@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
